snowflake:
  url: jdbc:snowflake://ku55653.ap-northeast-1.aws.snowflakecomputing.com/?warehouse=${snowflake.warehouse}&db=${snowflake.db}&private_key_file_pwd=${snowflake.password}&private_key_file=
  user: XXXXX
  warehouse: COMPUTE_WH
  db: SNOWFLAKE_SAMPLE_DATA  
  password: XXXXX
  keyfilename: rsa_key.p8