snowflake:
  url: jdbc:snowflake://XXXXXX.ap-northeast-1.aws.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=SNOWFLAKE_SAMPLE_DATA&private_key_file=/Users/{username}/AppData/Local/Temp/rsa_key.p8
  user: XXXXXX